// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTarget'](arg1, arg2, arg3, arg4);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function RemoveTarget(arg1) {
  return window['go']['main']['App']['RemoveTarget'](arg1);
}
