// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RemoveTarget(arg1:string):Promise<string>;
